name: Monorepo CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: ./packages/landing/out

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install project dependencies
        run: npm install

      - name: Build and test packages
        run: npm run build

      - name: List files in OUTPUT_DIR
        run: |
          ls -R ${{ env.OUTPUT_DIR }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.OUTPUT_DIR }}
